"""empty message

Revision ID: 06796c02da24
Revises: 073b3a3e8e58
Create Date: 2019-09-10 21:17:00.609016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06796c02da24'
down_revision = '073b3a3e8e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
