"""empty message

Revision ID: 073b3a3e8e58
Revises: 60c735df8d2f
Create Date: 2019-09-06 08:45:01.107447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073b3a3e8e58'
down_revision = '60c735df8d2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_date', 'end_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_sheets')
    # ### end Alembic commands ###
