"""empty message

Revision ID: 55fe5de0d6c4
Revises: 3b28b81949d0
Create Date: 2019-09-01 21:19:12.899078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55fe5de0d6c4'
down_revision = '3b28b81949d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE flate_rate_contracts RENAME TO flat_rate_contracts')
    op.create_unique_constraint(None, 'standard_contracts', ['client_id', 'start_date', 'room_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'standard_contracts', type_='unique')
    op.execute('ALTER TABLE flat_rate_contracts RENAME TO flate_rate_contracts')
    # ### end Alembic commands ###
