"""empty message

Revision ID: 60c735df8d2f
Revises: 88bb7e12da60
Create Date: 2019-09-06 08:27:03.082097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60c735df8d2f"
down_revision = "88bb7e12da60"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("payed_at", sa.Date(), nullable=True))
    op.add_column("invoices", sa.Column("check_number", sa.String(), nullable=True))
    op.add_column(
        "invoices", sa.Column("wire_transfer_number", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "wire_transfer_number")
    op.drop_column("invoices", "check_number")
    op.drop_column("invoices", "payed_at")
    # ### end Alembic commands ###
