"""empty message

Revision ID: 88bb7e12da60
Revises: 1ccc28bc41f8
Create Date: 2019-09-03 13:13:45.066280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "88bb7e12da60"
down_revision = "1ccc28bc41f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contracts", sa.Column("monthly_hours", sa.Integer(), nullable=True))
    op.add_column(
        "contracts", sa.Column("recurring_pricing_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "contracts", "pricings_recurring", ["recurring_pricing_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contracts", type_="foreignkey")
    op.drop_column("contracts", "recurring_pricing_id")
    op.drop_column("contracts", "monthly_hours")
    # ### end Alembic commands ###
