"""empty message

Revision ID: 99034f31271b
Revises: 
Create Date: 2019-08-30 09:11:22.644358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99034f31271b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name', 'last_name', 'email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('individual', sa.Boolean(), nullable=True),
    sa.Column('calendar_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'period')
    )
    op.create_table('standard_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'start_date', 'end_date')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('calendar_link', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('frozen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('calendar_link'),
    sa.UniqueConstraint('room_id', 'start_datetime', 'end_datetime')
    )
    op.create_table('exchange_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['standard_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flate_rate_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_hours', sa.String(), nullable=False),
    sa.Column('remaining_hours', sa.String(), nullable=False),
    sa.Column('hourly_rate', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['standard_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurrent_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_price', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['standard_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurrent_contracts')
    op.drop_table('flate_rate_contracts')
    op.drop_table('exchange_contracts')
    op.drop_table('bookings')
    op.drop_table('standard_contracts')
    op.drop_table('invoices')
    op.drop_table('rooms')
    op.drop_table('clients')
    # ### end Alembic commands ###
